# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

# Seerr - Unified media request management
# Multi-stage build matching upstream pattern: prod-deps + build + runtime

ARG BASE_VERSION=15.1
FROM ghcr.io/daemonless/base:${BASE_VERSION} AS base

# Build dependencies (shared across stages)
RUN pkg update && pkg install -y \
    node22 npm-node22 python3 py312-setuptools \
    gmake pkgconf sqlite3 vips \
    FreeBSD-clang FreeBSD-lld FreeBSD-toolchain FreeBSD-clibs-dev FreeBSD-runtime-dev \
    FreeBSD-zlib-dev FreeBSD-openssl-dev FreeBSD-xz-dev FreeBSD-bzip2-dev \
    ca_root_nss \
    && pkg clean -ay && rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

RUN ln -sf /usr/bin/clang /usr/bin/cc && \
    ln -sf /usr/bin/clang++ /usr/bin/c++

RUN corepack enable

ENV PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

# Build native addons against local node22 headers (no nodejs.org fetch -> no
# ECONNRESET); CPPFLAGS adds system libuv's uv.h, which node22's headers omit.
ENV npm_config_nodedir=/usr/local \
    CPPFLAGS=-I/usr/local/include
ENV NODE_OPTIONS="--max-old-space-size=2048"

# Download source
RUN SEERR_VERSION=$(fetch -qo - "https://api.github.com/repos/seerr-team/seerr/releases/latest" | jq -r '.tag_name') && \
    echo "Building Seerr ${SEERR_VERSION}" && \
    mkdir -p /app/seerr && \
    fetch -qo - "https://github.com/seerr-team/seerr/archive/refs/tags/${SEERR_VERSION}.tar.gz" | \
    tar xzf - -C /app/seerr --strip-components=1 && \
    echo "${SEERR_VERSION#v}" > /app/version

WORKDIR /app/seerr

# Next.js SWC patch for FreeBSD (no native binary): stub the downloads, force
# the WASM fallback first, drop the hard exit. Used by both prod-deps and build.
COPY <<'PATCH' /tmp/patch-swc.js
const fs = require('fs');
const p = process.argv[2];
fs.writeFileSync(p + '/dist/lib/download-swc.js',
  'module.exports.downloadNativeNextSwc=async function(){};module.exports.downloadWasmSwc=async function(){};');
let idx = fs.readFileSync(p + '/dist/build/swc/index.js', 'utf8');
idx = idx.replace(
  /shouldLoadWasmFallbackFirst\s*=\s*[^;]+;/,
  'shouldLoadWasmFallbackFirst = true;');
idx = idx.replace('process.exit(1)', '/* patched */');
fs.writeFileSync(p + '/dist/build/swc/index.js', idx);
console.log('SWC patched for FreeBSD WASM fallback');
PATCH

# Install the WASM SWC matching Next.js's minor and wire it into the next pkg.
# $1 = optional extra pnpm flags (e.g. --prod env uses --ignore-scripts already).
COPY <<'WASM' /usr/local/bin/setup-next-wasm.sh
#!/bin/sh
set -e
NEXT_DIR=$(ls -d node_modules/.pnpm/next@*/node_modules/next)
NEXT_VER=$(jq -r .version "${NEXT_DIR}/package.json")
NEXT_MINOR=$(echo "${NEXT_VER}" | sed 's/\.[0-9]*$//')
echo "Next.js ${NEXT_VER}: installing WASM SWC ~${NEXT_MINOR}.0"
pnpm add --ignore-scripts "@next/swc-wasm-nodejs@~${NEXT_MINOR}.0"
WASM_SRC=$(ls -d node_modules/.pnpm/@next+swc-wasm-nodejs@*/node_modules/@next/swc-wasm-nodejs)
mkdir -p "${NEXT_DIR}/wasm/@next/swc-wasm-nodejs"
cp -r "${WASM_SRC}"/* "${NEXT_DIR}/wasm/@next/swc-wasm-nodejs/"
node /tmp/patch-swc.js "${NEXT_DIR}"
WASM
RUN chmod +x /usr/local/bin/setup-next-wasm.sh

# seerr's next.config wires SVGR only for Turbopack. We build with --webpack
# (no FreeBSD native bindings), which ignores that, so SVG imports fall back to
# static images and crash SSR ("Element type is invalid"). Inject the equivalent
# webpack SVGR rule so SVGs become React components like Turbopack produces.
COPY <<'SVGR' /tmp/patch-svgr.js
const fs = require('fs');
const p = process.argv[2];
let s = fs.readFileSync(p, 'utf8');
const anchor = 'const nextConfig: NextConfig = {';
if (!s.includes(anchor)) { console.error('SVGR patch: anchor not found in ' + p); process.exit(1); }
const inject = `
  webpack(config) {
    const r = config.module.rules.find((x) => x.test && x.test.test && x.test.test('.svg'));
    if (r) {
      config.module.rules.push(
        { ...r, test: /\\.svg$/i, resourceQuery: /url/ },
        { test: /\\.svg$/i, issuer: r.issuer, resourceQuery: { not: [...((r.resourceQuery && r.resourceQuery.not) || []), /url/] }, use: ['@svgr/webpack'] }
      );
      r.exclude = /\\.svg$/i;
    } else {
      config.module.rules.push({ test: /\\.svg$/i, issuer: /\\.[jt]sx?$/, use: ['@svgr/webpack'] });
    }
    return config;
  },`;
fs.writeFileSync(p, s.replace(anchor, anchor + inject));
console.log('SVGR webpack rule injected into ' + p);
SVGR

# --- Stage: production dependencies ---
FROM base AS prod-deps
RUN CYPRESS_INSTALL_BINARY=0 pnpm install --prod --frozen-lockfile --ignore-scripts && \
    pnpm rebuild sqlite3 bcrypt && \
    setup-next-wasm.sh && \
    rm -rf $(pnpm store path)

# --- Stage: build ---
FROM base AS build

RUN CYPRESS_INSTALL_BINARY=0 pnpm install --frozen-lockfile

# WASM SWC (no native binary on FreeBSD) — same setup used by prod-deps.
RUN setup-next-wasm.sh

# next build defaults to Turbopack (no FreeBSD native bindings) -> force webpack,
# and add the SVGR webpack rule that the Turbopack-only config would otherwise skip.
RUN node /tmp/patch-svgr.js next.config.ts && \
    node_modules/.bin/next build --webpack && \
    pnpm build:server && \
    rm -rf .next/cache $(pnpm store path)

# --- Stage: production image ---
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="node22 vips sqlite3"
ARG UPSTREAM_URL="https://api.github.com/repos/seerr-team/seerr/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:5055/api/v1/status"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Seerr" \
      org.opencontainers.image.description="Unified media request management (Plex, Jellyfin, Emby) on FreeBSD." \
      org.opencontainers.image.source="https://github.com/daemonless/seerr" \
      org.opencontainers.image.url="https://seerr.io/" \
      org.opencontainers.image.documentation="https://docs.seerr.io/" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Media Management" \
      io.daemonless.port="5055" \
      io.daemonless.volumes="/config" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

# Runtime dependencies only
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Copy full source tree, then overlay prod deps and build output (matching upstream)
COPY --from=base --chown=bsd:bsd /app/seerr /app/seerr
COPY --from=base --chown=bsd:bsd /app/version /app/version
COPY --from=prod-deps --chown=bsd:bsd /app/seerr/node_modules /app/seerr/node_modules
COPY --from=build --chown=bsd:bsd /app/seerr/.next /app/seerr/.next
COPY --from=build --chown=bsd:bsd /app/seerr/dist /app/seerr/dist

# Fix fresh-install crash: enable synchronize (creates schema) and skip broken migrations
RUN node -e "let f='/app/seerr/dist/datasource.js',s=require('fs').readFileSync(f,'utf8');require('fs').writeFileSync(f,s.replace('synchronize: false','synchronize: true'))" && \
    node -e "let f='/app/seerr/dist/index.js',s=require('fs').readFileSync(f,'utf8');require('fs').writeFileSync(f,s.replace(/await dbConnection\.runMigrations\(\)/g,'/* migrations handled by synchronize */'))"

# Create config directory
RUN mkdir -p /config && chown bsd:bsd /config

# Copy service files
COPY root/ /
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 5055

# --- Volumes (Injected by Generator) ---
VOLUME /config