#!/bin/sh
# Seerr s6 service

export HOME=/config
export NODE_ENV=production
export CONFIG_DIRECTORY=/config
export PORT=5055

# Signal readiness when the port is responsive
s6-ready-when fetch -qo /dev/null http://localhost:5055/

cd /app/seerr
exec /usr/local/bin/s6-setuidgid bsd /usr/local/bin/node dist/index.js
